import { motion, useScroll, useTransform, useReducedMotion } from 'framer-motion'
import { useRef } from 'react'
import { SCENARIO_RESULTS } from '../data/seed'
import { rise, useParallax } from '../lib/motion'
import { AsteriskBadge, Starburst } from './art/Stickers'
import { Watchman } from './art/Watchman'
import { EvasionChart } from './EvasionChart'

export function Misses() {
  const introRef = useRef<HTMLDivElement>(null)
  const reduce = useReducedMotion()
  const { scrollYProgress } = useScroll({ target: introRef, offset: ['start end', 'end start'] })
  const spin = useTransform(scrollYProgress, [0, 1], reduce ? [0, 0] : [-40, 80])
  const burstY = useParallax(introRef, 70)
  return (
    <section id="misses" className="misses on-dark" aria-labelledby="misses-title">
      <Watchman />
      <div className="wrap">
        <div className="misses__intro" ref={introRef}>
          <motion.div className="sticker sticker--burst" style={{ rotate: spin, y: burstY }} aria-hidden>
            <Starburst />
          </motion.div>
          <motion.div className="sticker sticker--asterisk" style={{ rotate: spin }} aria-hidden>
            <AsteriskBadge />
          </motion.div>
          <motion.h2 id="misses-title" className="heading misses__title" {...rise()}>
            A watchman that says what it did not see.
          </motion.h2>
          <motion.p className="section-lede misses__lede" {...rise(0.08)}>
            Six attacks are planted in every dataset. Prahari catches four on every seed and misses two on every seed.
            Then an attacker who knows how it works spends a budget to hide. These numbers are generated by the CLI and
            never edited by hand.
          </motion.p>
        </div>

        <ol className="scenarios">
          {SCENARIO_RESULTS.map((s, i) => (
            <motion.li key={s.id} className={s.detected ? '' : 'is-miss'} {...rise(i * 0.05, 16)}>
              <span className="scenarios__id">{s.id}</span>
              <span className="scenarios__name">
                {s.name}
                {'why' in s && <span className="scenarios__why">{s.why}</span>}
              </span>
              <span className="scenarios__bar" role="img" aria-label={`Detected on ${s.detected} of 10 seeds`}>
                {Array.from({ length: 10 }, (_, k) => (
                  <span key={k} className={k < s.detected ? 'is-on' : ''} />
                ))}
              </span>
              <span className="scenarios__score tnum">{s.detected}/10</span>
              <span className="scenarios__rank tnum">{s.rank ? `rank ${s.rank}` : 'missed'}</span>
            </motion.li>
          ))}
        </ol>

        <motion.div {...rise()}>
          <h3 className="heading-sm misses__sub">Against an adaptive attacker</h3>
          <EvasionChart />
        </motion.div>

        <motion.ul className="misses__facts" {...rise()}>
          <li>
            <span className="tnum">0.37 ± 0.17</span> pairwise precision. Prahari over-merges; the cohesion badge is how it
            tells you.
          </li>
          <li>
            <span className="tnum">0.64 ± 0.05</span> of the top ten incidents are background noise rather than a planted
            attack.
          </li>
          <li>
            <span className="tnum">0.88 ± 0.01</span> less time to reach the first real attack than reading alerts in
            timestamp order.
          </li>
        </motion.ul>
      </div>
    </section>
  )
}
